config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rentals
end

app/models/cat.rb
require 'date'

class Cat < ActiveRecord::Base
  validates :name, presence:true
  validates :birth_date, presence: true
  validates :color, inclusion: { in: %w(black white orange tabby tortishell)}
  validates :sex, inclusion: { in: %w(M F) }

  has_many :cat_rental_requests, dependent: :destroy

  def age
    (Time.now.to_date - self.birth_date) / 365
  end
end

app/models/cat_rental_request.rb
require 'date'

class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED)}

  validate :overlapping_approved_requests

  belongs_to :cat

  def overlapping_requests
    cat.cat_rental_requests.select do |crr|
      self.start_date.between?(crr.start_date, crr.end_date) || self.end_date.between?(crr.start_date, crr.end_date)
    end
  end

  def overlapping_approved_requests
    overlap_check = overlapping_requests.none? do |overlapping_request|
      overlapping_request.status == "APPROVED"
    end
    if overlap_check == false
      errors[:overlapping] << "Request overlaps with another approved request"
    else
      return true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rentals_controller.rb
class CatRental < ApplicationController

  def new

  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new(name: '', birth_date: '', color: '', sex: 'M')
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end

  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def destroy
    @cat = Cat.find(params[:id])

    if @cat.destroy!
      redirect_to "/cats"
    else
      flash[:error] = "We were unable to destroy the Item"
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<!-- <form action="/cats" method="post">
   <input type="hidden" name="_method" value="PATCH"> -->

<% action_url = (action == :new) ? cats_url : cat_url(@cat) %>

   <form action="<%= action_url %>" method="post">
     <% if action == :edit %>
       <input type="hidden" name="_method" value="patch">
     <% end %>

  <label>Name
      <input type="text" name="cat[name]" value=<%=@cat.name%>>
  </label>
  <br>

  <label>Sex
    <input type="radio" name="cat[sex]" value="M" <%="checked" if @cat.sex == "M"%>>Male
    <input type="radio" name="cat[sex]" value="F" <%="checked" if @cat.sex == "F"%>>Female
  </label>
 <br>
  <label>Color
    <select name="cat[color]">
       <% if action == :new %>
        <option value="Select Color" disabled="true" selected="true">Select Color</option>
      <% end %>

        <% color = @cat.color %>
        <option value="white" <%= "selected='true'" if color == "white"%> >White</option>
        <option value="black" <%= "selected='true'" if color == "black"%>>Black</option>
        <option value="orange" <%= "selected='true'" if color == "orange"%>>Orange</option>
        <option value="tabby" <%= "selected='true'" if color == "tabby"%>>Tabby</option>
        <option value="tortishell" <%= "selected='true'" if color == "tortishell"%>>tortishell</option>
    </select>
  </label>
  <br>

  <label>Birthdate
      <input type="date" name="cat[birth_date]" value=<%= @cat.birth_date%>>
  </label>
  <br>

  <label>Description
      <textarea name="cat[description]" cols="30" rows="10"><%=@cat.description%></textarea>
  </label>

  <input type="submit" value="Create Cat!">

</form>

app/views/cats/edit.html.erb
<%= render "form", cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1> here are the cats test </h1>
<h2> <% @cats.each do |cat| %> </h2>
<%= link_to "#{cat.name}", "cats/#{cat.id}" %>
<p> <% end %> </p>

app/views/cats/new.html.erb
<!-- Use text for name.
Use radio buttons for sex.
Use a drop down for color.
Use a blank <option> as the default color; this will force the user to consciously pick one.
You can use the date input type to prompt the user to pick a birth date. Look this up on MDN.
Use a textarea tag for the description. -->
<%= render "form", action: :new, cat: @cat %>

<!--
<form action="/cats" method="post">
  <label>Name
    <input type="text" name="cat[name]">
  </label>
  <br>
  <label>Sex
    <input type="radio" name="cat[sex]" value="M" checked>Male
    <input type="radio" name="cat[sex]" value="F">Female
  </label>
 <br>
  <label>Color
    <select name="cat[color]">
        <option value="Select Color" disabled="true" selected="true">Select Color</option>
        <option value="white">White</option>
        <option value="black">Black</option>
        <option value="orange">Orange</option>
        <option value="tabby">Tabby</option>
        <option value="tortishell">tortishell</option>
    </select>
  </label>
  <br>

  <label>Birthdate
    <input type="date" name="cat[birth_date]">
  </label>
  <br>

  <label>Description
    <textarea name="cat[description]" cols="30" rows="10"></textarea>
  </label>

  <input type="submit" value="Create Cat!">

</form> -->

app/views/cats/show.html.erb
<h2> show page </h2>

<table border='1'>


  <tr>
    <th>Name</th>
    <td> <%= @cat.name %> </td>
  </tr>
  <tr>
    <th>Color</th>
    <td> <%= @cat.color %> </td>
  </tr>
  <tr>
    <th>Birthdate</th>
    <td> <%= @cat.birth_date %> </td>
  </tr>
  <tr>
    <th>Sex</th>
    <td> <%= @cat.sex %> </td>
  </tr>
  <tr>
    <th>Description</th>
    <td> <%= @cat.description %> </td>
  </tr>
</table>

<form action=<%=cat_url(@cat)%> method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete Cat!">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>